### ISSUE TITLE
Posts reflect date of writing, not date of publishing

### ISSUE THREAD

**Issue by Daniel-Worrall** [y32/y32.github.io#21]
The filename is used as reference to the date the blog post is written and posted, but if the merge happens on a different day, it is posted to the blog but appears as if it was posted earlier. Going forward, we could either have planned days to post/merge or amend the date on merge.

**Comment by z64** [comment]
I look at this as the date it was written, not the date published (two different things). It's pretty inconsequential.

We can adopt some kind of practice if the others care. I don't mind either way, but it seems tedious to modify the date prior to merging.

**Comment by unleashy** [comment]
I'd prefer date of publishing tbqh

**Comment by Cyan101** [comment]
I agree with date of publication over creation
